#!/bin/bash

POWER=$(ls /sys/class/power_supply/)
echo "$POWER"

CHARGE=$(cat /sys/class/power_supply/$POWER/capacity)
STATUS=$(cat /sys/class/power_supply/$POWER/status)

if [ "$POWER" = "AC" ]; then
	echo "AC"
elif [ "$STATUS" = "Charging" ] || [ "$STATUS" = "Full" ]; then
	echo " $CHARGE%" 
elif [ "$CHARGE" -ge 90 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 90 ] && [ "$CHARGE" -ge 65 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 65 ] && [ "$CHARGE" -ge 45 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 45 ] && [ "$CHARGE" -ge 15 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 15 ]; then
	echo " $CHARGE%"
fi
