#!/bin/bash

case $BUTTON in
	1) $TERMINAL -e gotop ;;
	3) $TERMINAL -e "$EDITOR" "$0" ;;
esac

AC=$(cat /sys/class/power_supply/AC/online)
POWER=$(ls /sys/class/power_supply/ | grep BAT*)
CHARGE=$(cat /sys/class/power_supply/$POWER/capacity)
STATUS=$(cat /sys/class/power_supply/$POWER/status)

if [ "$STATUS" = "Charging" ] || [ "$STATUS" = "Full" ]; then
	echo " $CHARGE%" 
elif [ "$CHARGE" -ge 90 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 90 ] && [ "$CHARGE" -ge 65 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 65 ] && [ "$CHARGE" -ge 45 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 45 ] && [ "$CHARGE" -ge 15 ]; then
	echo " $CHARGE%"
elif [ "$CHARGE" -lt 15 ]; then
	echo " $CHARGE%"
elif [ "$AC" = "1" ]; then
	echo "AC"
else
	echo "Problem AC/Battery"
fi
