#!/bin/sh

case $BUTTON in
	1) $TERMINAL ;;
	3) $TERMINAL -e "$EDITOR" "$0" ;;
esac

DISTRO="$(cat /etc/os-release | sed -n 1p | awk -F '"' '{print $2}')"

if [ "$DISTRO" = "void" ]; then
	updates=$(xbps-install -Suvn | wc -l)

elif [ "$DISTRO" = "Arch Linux" ]; then
	#updatesarch="$(checkupdates 2> /dev/null | wc -l)"
	updatearch="$(pacman -Qu | wc -l)"
	updatesaur="$(yay -Qum 2> /dev/null | wc -l)"
	updates=$(("$updatesarch" + "$updatesaur"))
fi

echo " $((updates))"
